-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."account_currencies" AS ENUM('USD', 'EUR', 'CNY', 'GBP');--> statement-breakpoint
CREATE TYPE "public"."admin_notification_variants" AS ENUM('NEW_COMPLAINT', 'NEW_REVIEW', 'NEW_VENDOR_REGISTER', 'NEW_REFUND', 'NEW_NEGATIVE_REVIEW');--> statement-breakpoint
CREATE TYPE "public"."app_types" AS ENUM('IOS', 'ANDROID', 'ADMIN', 'WEB');--> statement-breakpoint
CREATE TYPE "public"."audit_actions" AS ENUM('INSERT', 'UPDATE', 'DELETE');--> statement-breakpoint
CREATE TYPE "public"."complaint_state_variants" AS ENUM('DECLINED', 'ACCEPTED', 'IN_REVIEW');--> statement-breakpoint
CREATE TYPE "public"."data_type_variants" AS ENUM('TEXT', 'BOOL', 'NUMBER');--> statement-breakpoint
CREATE TYPE "public"."discount_variants" AS ENUM('PERCENT', 'FIX');--> statement-breakpoint
CREATE TYPE "public"."language_variants" AS ENUM('RU', 'EN', 'CH');--> statement-breakpoint
CREATE TYPE "public"."manager_types" AS ENUM('CONTENT_MANAGER', 'ADMIN');--> statement-breakpoint
CREATE TYPE "public"."media_types" AS ENUM('VIDEO', 'IMAGE', 'FILE');--> statement-breakpoint
CREATE TYPE "public"."message_variants" AS ENUM('USER', 'SYSTEM');--> statement-breakpoint
CREATE TYPE "public"."orders_states" AS ENUM('CREATED', 'PACKED', 'DELIVERED', 'SUCCEED', 'CANCELED');--> statement-breakpoint
CREATE TYPE "public"."payment_methods" AS ENUM('CARD');--> statement-breakpoint
CREATE TYPE "public"."permit_directories" AS ENUM('ORDERS', 'DISCOUNTS', 'FINANCES', 'REFUNDS', 'CATEGORIES', 'REVIEWS');--> statement-breakpoint
CREATE TYPE "public"."permit_levels" AS ENUM('READ', 'CREATE', 'UPDATE', 'DELETE');--> statement-breakpoint
CREATE TYPE "public"."product_complaint_variants" AS ENUM('INCORRECT_PRICE', 'INCORRECT_INFO', 'VENDOR_NOT_ANSWER', 'VIOLATES_TOS', 'FRAUD', 'OFFENSIVE_SPEAK', 'FORBIDDEN_SUBSTANCES', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."product_custom_prop_variants" AS ENUM('BOOL');--> statement-breakpoint
CREATE TYPE "public"."product_refund_reason_variants" AS ENUM('DEFECTIVE_PRODUCT', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."product_refund_state_variants" AS ENUM('PENDING', 'REJECTED', 'ACCEPTED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."product_sub_bills_state_variants" AS ENUM('PENDING', 'SUCCEED', 'FAILURE');--> statement-breakpoint
CREATE TYPE "public"."product_subscriber_states" AS ENUM('ACTIVE', 'CANCELLED', 'AWAITING');--> statement-breakpoint
CREATE TYPE "public"."product_variants" AS ENUM('SUBSCRIPTION', 'ONE_TIME', 'GOOD');--> statement-breakpoint
CREATE TYPE "public"."review_state_variants" AS ENUM('PENDING', 'REJECTED', 'PUBLISHED');--> statement-breakpoint
CREATE TYPE "public"."system_notification_variants" AS ENUM('COMPLAINT_CREATED', 'REVIEW_CREATED', 'NEGATIVE_REVIEW_CREATED', 'VENDOR_REGISTER', 'PRODUCT_REFUND_CREATED');--> statement-breakpoint
CREATE TYPE "public"."transaction_status_variants" AS ENUM('PENDING', 'SUCCEED', 'FAILURE');--> statement-breakpoint
CREATE TYPE "public"."user_type_variants" AS ENUM('MANAGER', 'CLIENT', 'VENDOR');--> statement-breakpoint
CREATE TYPE "public"."user_types" AS ENUM('MANAGER', 'CLIENT', 'COURIER');--> statement-breakpoint
CREATE TYPE "public"."vendor_account_transaction_variants" AS ENUM('PAYOUT', 'ACCRUAL', 'ADJUSTING');--> statement-breakpoint
CREATE TYPE "public"."vendor_legal_form_variants" AS ENUM('COMPANY', 'INDIVIDUAL', 'SELF_EMPLOYED');--> statement-breakpoint
CREATE TYPE "public"."vendor_payout_request_state_variants" AS ENUM('PENDING', 'REJECTED', 'SUCCEED', 'CANCELLED');--> statement-breakpoint
CREATE TABLE "app_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"type" "app_types",
	"version" varchar(15),
	"is_major" boolean,
	"is_production" boolean,
	"users_count" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"table_name" varchar(100) NOT NULL,
	"record_id" bigint NOT NULL,
	"action" "audit_actions" NOT NULL,
	"old_data" jsonb,
	"new_data" jsonb,
	"actor_id" integer,
	"actor_type" "user_type_variants",
	"ip_address" varchar(45)
);
--> statement-breakpoint
CREATE TABLE "client_payout_requests" (
	"cprid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_payout_requests_cprid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"payout_request_state_variant" "vendor_payout_request_state_variants" NOT NULL,
	"cid" integer NOT NULL,
	"amount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"cpr" integer NOT NULL,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "client_referrals" (
	"crid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_referrals_crid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"expires_at" timestamp,
	"primary_rate_volume" smallint DEFAULT 0 NOT NULL,
	"personal_rate_volume" smallint DEFAULT 0 NOT NULL,
	"owner_cid" integer NOT NULL,
	"refferer_cid" integer NOT NULL,
	"is_operational" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"cid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clients_cid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"name" varchar(50),
	"email" varchar(254),
	"phone" varchar(20),
	"partners_code" varchar(100),
	"is_allow_mailing" boolean,
	"firebase_push_token" varchar(1000),
	"is_push_enabled" boolean,
	"is_mailing_enabled" boolean,
	"allow_order_notifications" boolean DEFAULT true,
	"is_banned" boolean DEFAULT false,
	"ban_reason" varchar(500),
	"avatar_id" integer,
	"is_archived" boolean DEFAULT false,
	CONSTRAINT "clients_email_key" UNIQUE("email"),
	CONSTRAINT "clients_phone_key" UNIQUE("phone"),
	CONSTRAINT "clients_partners_code_key" UNIQUE("partners_code")
);
--> statement-breakpoint
CREATE TABLE "client_payout_requisites" (
	"cpr" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_payout_requisites_cpr_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"cid" integer NOT NULL,
	"bank_name" varchar(100),
	"bank_code" varchar(20),
	"bank_swift" varchar(11),
	"bank_address" varchar(200),
	"bank_account_number" varchar(100),
	"bank_account_holder" varchar(100),
	"bank_bik" varchar(9),
	"bank_inn" varchar(12),
	"bank_korr_number" varchar(17),
	"comment" varchar(100),
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "client_referrals_account_transactions" (
	"crid" integer,
	"created_at" timestamp DEFAULT now(),
	"total_amount" numeric(15, 2) DEFAULT '0' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "product_refunds" (
	"prfid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_refunds_prfid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"cid" integer NOT NULL,
	"oid" integer,
	"pid" integer NOT NULL,
	"product_refund_state_variant" "product_refund_state_variants" DEFAULT 'PENDING',
	"comment" text,
	"reason" text,
	"product_refund_reason_variant" "product_refund_reason_variants",
	"refund_product_count" integer,
	"is_refund_complete" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "bank_card_tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bank_card_tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"expires_at" timestamp,
	"token" varchar(200),
	"caid" integer,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "vendor_requisites" (
	"vrqid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_requisites_vrqid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vid" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"name" varchar(200),
	"fiscal_number" varchar(20) NOT NULL,
	"tax_id" varchar(50) NOT NULL,
	"contact_form" varchar(20),
	"contact_email" varchar(255),
	"primary_person_name" varchar(100),
	"accountant_name" varchar(100),
	"comment" varchar(1000),
	"vendor_legal_form_variant" "vendor_legal_form_variants" NOT NULL,
	"is_archived" boolean DEFAULT false,
	CONSTRAINT "vendor_requisites_fiscal_number_key" UNIQUE("fiscal_number"),
	CONSTRAINT "vendor_requisites_tax_id_key" UNIQUE("tax_id")
);
--> statement-breakpoint
CREATE TABLE "vendors" (
	"vid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendors_vid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"name" varchar(100),
	"email" varchar(255),
	"phone" varchar(20),
	"is_allow_mailing" boolean,
	"firebase_push_token" varchar(1000),
	"is_push_enabled" boolean,
	"is_mailing_enabled" boolean,
	"is_banned" boolean DEFAULT false,
	"ban_reason" varchar(200),
	"avatar_id" integer,
	"is_archived" boolean DEFAULT false,
	CONSTRAINT "vendors_email_key" UNIQUE("email"),
	CONSTRAINT "vendors_phone_key" UNIQUE("phone")
);
--> statement-breakpoint
CREATE TABLE "vendor_account_transactions" (
	"vatid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_account_transactions_vatid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"vaid" integer NOT NULL,
	"total_amount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"fee_amount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"vendor_account_transaction_variant" "vendor_account_transaction_variants" NOT NULL,
	"transaction_status_variant" "transaction_status_variants" NOT NULL,
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vendor_payout_requests" (
	"vprid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_payout_requests_vprid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"vaid" integer NOT NULL,
	"total_amount" numeric(15, 2) DEFAULT '0' NOT NULL,
	"vbrid" integer,
	"vendor_payout_request_state_variant" "vendor_payout_request_state_variants" DEFAULT 'PENDING'
);
--> statement-breakpoint
CREATE TABLE "confirmation_sms_codes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "confirmation_sms_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"expires_at" timestamp NOT NULL,
	"phone" varchar(20) NOT NULL,
	"code_hash" varchar(1000) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "client_addresses" (
	"caid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_addresses_caid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"client_id" integer,
	"lat" double precision,
	"lng" double precision,
	"city" varchar(100),
	"street" varchar(100),
	"house_num" smallint,
	"flat_num" integer,
	"stage" integer,
	"entrance" integer,
	"comment" varchar(1000),
	"transport_company" integer,
	"is_primary" boolean,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "media" (
	"mid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_mid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"description" varchar(500),
	"path" varchar(1000) NOT NULL,
	"media_type" "media_types",
	"is_archived" boolean DEFAULT false,
	CONSTRAINT "media_path_key" UNIQUE("path")
);
--> statement-breakpoint
CREATE TABLE "vendor_phone_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_phone_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"phone" varchar(20) NOT NULL,
	"vendor_id" integer,
	CONSTRAINT "vendor_phone_auth_phone_key" UNIQUE("phone")
);
--> statement-breakpoint
CREATE TABLE "clients_phone_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clients_phone_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"phone" varchar(20) NOT NULL,
	"client_id" integer,
	CONSTRAINT "clients_phone_auth_phone_key" UNIQUE("phone")
);
--> statement-breakpoint
CREATE TABLE "managers" (
	"maid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "managers_maid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"manager_type" "manager_types",
	"name" varchar(250),
	"login" varchar(255) NOT NULL,
	"email" varchar(255),
	"is_banned" boolean DEFAULT false,
	"is_archived" boolean DEFAULT false,
	CONSTRAINT "managers_login_key" UNIQUE("login"),
	CONSTRAINT "managers_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "product_prices" (
	"ppid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_prices_ppid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"pid" integer NOT NULL,
	"price" numeric(15, 2) NOT NULL,
	"duration" double precision,
	"description" varchar(300),
	"country_id" integer NOT NULL,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "manager_password_auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "manager_password_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"login" varchar(255) NOT NULL,
	"password_sha256" varchar(1000),
	"manager_id" integer,
	CONSTRAINT "manager_password_auth_login_key" UNIQUE("login")
);
--> statement-breakpoint
CREATE TABLE "products" (
	"pid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_pid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"product_slug" varchar(500) NOT NULL,
	"article_number" varchar(50),
	"vendor_owner_id" integer,
	"base_volume" double precision,
	"volume_dimension" varchar(10),
	"pcid" integer,
	"length" double precision,
	"width" double precision,
	"height" double precision,
	"weight" double precision,
	"color_hex" varchar(50),
	"package_size" varchar(10),
	"country_id" integer,
	"brand_id" integer,
	"product_variant" "product_variants" DEFAULT 'GOOD' NOT NULL,
	"is_archived" boolean DEFAULT false,
	"is_visible" boolean DEFAULT true,
	CONSTRAINT "products_product_slug_key" UNIQUE("product_slug"),
	CONSTRAINT "products_article_number_key" UNIQUE("article_number")
);
--> statement-breakpoint
CREATE TABLE "product_subscribers" (
	"psid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_subscribers_psid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pid" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"cancelled_at" timestamp,
	"next_payment_at" timestamp,
	"cid" integer,
	"product_price" integer NOT NULL,
	"product_subscriber_state" "product_subscriber_states" DEFAULT 'AWAITING'
);
--> statement-breakpoint
CREATE TABLE "product_sub_bills" (
	"psbid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_sub_bills_psbid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"psid" integer NOT NULL,
	"total" numeric(15, 2) NOT NULL,
	"product_sub_bills_state_variant" "product_sub_bills_state_variants" DEFAULT 'PENDING'
);
--> statement-breakpoint
CREATE TABLE "product_reviews" (
	"prid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_reviews_prid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"cid" integer,
	"pid" integer NOT NULL,
	"text" text,
	"rate_volume" smallint NOT NULL,
	"is_archived" boolean DEFAULT false,
	"is_visible" boolean DEFAULT true,
	"vendor_answer" text,
	"vendor_answer_updated_at" timestamp,
	"review_state_variant" "review_state_variants" DEFAULT 'PENDING'
);
--> statement-breakpoint
CREATE TABLE "client_reviews" (
	"crid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_reviews_crid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"to_cid" integer,
	"from_vid" integer,
	"text" text,
	"rate_volume" smallint NOT NULL,
	"is_archived" boolean DEFAULT false,
	"is_visible" boolean DEFAULT true,
	"review_state_variant" "review_state_variants" DEFAULT 'PENDING'
);
--> statement-breakpoint
CREATE TABLE "product_categories" (
	"pcid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_categories_pcid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"parent_category_id" integer,
	"is_archived" boolean DEFAULT false,
	"is_visible" boolean DEFAULT true,
	"category_slug" varchar(300) NOT NULL,
	CONSTRAINT "product_categories_category_slug_key" UNIQUE("category_slug")
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"oid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orders_oid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"client_id" integer,
	"total_amount" numeric(15, 2),
	"order_state" "orders_states",
	"packages" integer,
	"weight_kg" double precision,
	"client_address_id" integer,
	"cpmid" integer,
	"comment" varchar(1000),
	"is_archived" boolean DEFAULT false,
	"delivery_track_num" varchar(30),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "global_discounts" (
	"gdid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "global_discounts_gdid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"starts_at" timestamp,
	"expires_at" timestamp,
	"discount_amount" numeric(15, 2),
	"discount_variant" "discount_variants",
	"min_order_amount" integer,
	"name" varchar(200),
	"description" varchar(2000),
	"is_archived" boolean DEFAULT false,
	"is_draft" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "local_discounts" (
	"ldid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "local_discounts_ldid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"starts_at" timestamp,
	"expires_at" timestamp,
	"discount_amount" numeric(15, 2),
	"discount_variant" "discount_variants",
	"min_order_amount" numeric(15, 2),
	"name" varchar(200),
	"description" varchar(2000),
	"vid" integer,
	"is_archived" boolean DEFAULT false,
	"is_draft" boolean DEFAULT true,
	"is_pending" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "order_to_products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_to_products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer,
	"order_id" integer,
	"volume" integer
);
--> statement-breakpoint
CREATE TABLE "recommended_products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recommended_products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"product_id" integer,
	"recommended_good_id" integer,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "product_complaints" (
	"psid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_complaints_psid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"cid" integer NOT NULL,
	"text" text,
	"pid" integer NOT NULL,
	"complaint_variant" "product_complaint_variants" NOT NULL,
	"complaint_state_variant" "complaint_state_variants" DEFAULT 'IN_REVIEW' NOT NULL,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "article_publications" (
	"apid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "article_publications_apid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"is_published" boolean DEFAULT true,
	"is_archived" boolean DEFAULT false,
	"slug" varchar(300)
);
--> statement-breakpoint
CREATE TABLE "admin_notifications" (
	"anid" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_notifications_anid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"sent_at" timestamp,
	"admin_notification_variant" "admin_notification_variants" NOT NULL,
	"title" varchar(200),
	"cid" integer,
	"pid" integer,
	"prid" integer,
	"pcid" integer,
	"vid" integer,
	"prfid" integer,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "auth_sessions" (
	"asid" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_sessions_asid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"client_id" integer,
	"manager_id" integer,
	"vendor_id" integer,
	"type" "user_type_variants",
	"refresh_token" varchar(2000) NOT NULL,
	"is_active" boolean DEFAULT true,
	"last_ip_address" varchar(30),
	"last_refresh_token_time" timestamp
);
--> statement-breakpoint
CREATE TABLE "vendor_complaints" (
	"vcid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_complaints_vcid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"cid" integer NOT NULL,
	"text" text,
	"vid" integer NOT NULL,
	"complaint_variant" "product_complaint_variants" NOT NULL,
	"complaint_state_variant" "complaint_state_variants" DEFAULT 'IN_REVIEW' NOT NULL,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "user_geolocations" (
	"uglid" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_geolocations_uglid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cid" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"lat" double precision NOT NULL,
	"lng" double precision NOT NULL,
	"accuracy" smallint
);
--> statement-breakpoint
CREATE TABLE "news_publications" (
	"npid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "news_publications_npid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"is_published" boolean DEFAULT true,
	"is_archived" boolean DEFAULT false,
	"slug" varchar(300)
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"convid" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversations_convid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"pid" integer,
	"oid" integer,
	"avatar_mid" integer,
	"last_message_text" varchar(200),
	"last_message_at" timestamp,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "product_category_props" (
	"pcpid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_category_props_pcpid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"pcid" integer,
	"code" varchar(20),
	"order" smallint,
	"data_type_variant" "data_type_variants" NOT NULL,
	"is_archived" boolean DEFAULT false,
	"is_required" boolean DEFAULT false,
	"is_visible" boolean DEFAULT false,
	"is_filtering" boolean
);
--> statement-breakpoint
CREATE TABLE "integration_specs" (
	"isid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "integration_specs_isid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"service_name" varchar(100),
	"service_description" varchar(100),
	"api_key" varchar(1000)
);
--> statement-breakpoint
CREATE TABLE "d_countries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "d_countries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "d_brands" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "d_brands_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "conv_participants" (
	"convpid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conv_participants_convpid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"convid" bigint NOT NULL,
	"vid" integer,
	"cid" integer,
	"maid" integer,
	"last_read_mesid" integer
);
--> statement-breakpoint
CREATE TABLE "conv_messages" (
	"mesid" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conv_messages_mesid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"archived_at" timestamp,
	"text" text,
	"convid" bigint NOT NULL,
	"vid" integer,
	"cid" integer,
	"maid" integer,
	"message_variant" "message_variants",
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "access_permits" (
	"apid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "access_permits_apid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"name" varchar(200),
	"permit_level" "permit_levels"[],
	"permit_directories" "permit_directories"[],
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "d_custom" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "d_custom_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "manager_notifications" (
	"notification_id" bigint NOT NULL,
	"read_at" timestamp,
	"manager_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vendor_bank_requisites" (
	"vbrid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_bank_requisites_vbrid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vid" integer NOT NULL,
	"vrqid" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"bank_name" varchar(50),
	"bank_code" varchar(10),
	"bank_swift" varchar(11),
	"bank_address" varchar(200),
	"bank_account_number" varchar(20),
	"bank_account_holder" varchar(50),
	"bank_bik" varchar(9),
	"bank_inn" varchar(17),
	"bank_korr_number" varchar(20),
	"comment" varchar(1000),
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "vendor_accounts" (
	"vaid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_accounts_vaid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vid" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"started_at" timestamp,
	"suspended_at" timestamp,
	"account_currency" "account_currencies" NOT NULL,
	"fee_default" numeric(15, 2) DEFAULT '0',
	"is_archived" boolean DEFAULT false,
	"is_suspended" boolean DEFAULT false,
	"is_verified" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "d_transport_companies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "d_transport_companies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "product_custom_props" (
	"pcpid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_custom_props_pcpid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"value" jsonb NOT NULL,
	"is_archived" boolean DEFAULT false,
	"is_visible" boolean DEFAULT true
);
--> statement-breakpoint
CREATE TABLE "client_payment_methods" (
	"cpmid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "client_payment_methods_cpmid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	"client_id" integer,
	"type" "payment_methods",
	"credentials" varchar(1000),
	"description" varchar(2000),
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "vendor_reviews" (
	"vrid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_reviews_vrid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"to_vid" integer,
	"from_cid" integer,
	"text" text,
	"rate_volume" smallint NOT NULL,
	"is_visible" boolean DEFAULT true,
	"review_state_variant" "review_state_variants" DEFAULT 'PENDING',
	"is_archived" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "system_notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"system_notification_variant" "system_notification_variants" NOT NULL,
	"title" varchar(100),
	"topic" varchar(50),
	"description" varchar(1000),
	"vid" integer,
	"prid" integer,
	"complaint_id" integer,
	"prfid" integer
);
--> statement-breakpoint
CREATE TABLE "product_refund_media" (
	"mid" integer NOT NULL,
	"prfid" integer NOT NULL,
	CONSTRAINT "product_refund_media_pkey" PRIMARY KEY("mid","prfid")
);
--> statement-breakpoint
CREATE TABLE "product_props" (
	"pid" integer NOT NULL,
	"pcpid" integer NOT NULL,
	CONSTRAINT "product_props_pkey" PRIMARY KEY("pid","pcpid")
);
--> statement-breakpoint
CREATE TABLE "product_review_media" (
	"prid" integer NOT NULL,
	"mid" integer NOT NULL,
	CONSTRAINT "product_review_media_pkey" PRIMARY KEY("prid","mid")
);
--> statement-breakpoint
CREATE TABLE "client_review_media" (
	"crid" integer NOT NULL,
	"mid" integer NOT NULL,
	CONSTRAINT "client_review_media_pkey" PRIMARY KEY("crid","mid")
);
--> statement-breakpoint
CREATE TABLE "category_discounts" (
	"discount_id" integer NOT NULL,
	"pcid" integer NOT NULL,
	CONSTRAINT "category_discounts_pkey" PRIMARY KEY("discount_id","pcid")
);
--> statement-breakpoint
CREATE TABLE "vendor_product_discounts" (
	"ldid" integer NOT NULL,
	"pid" integer NOT NULL,
	CONSTRAINT "vendor_product_discounts_pkey" PRIMARY KEY("ldid","pid")
);
--> statement-breakpoint
CREATE TABLE "product_complaint_media" (
	"psid" integer NOT NULL,
	"mid" integer NOT NULL,
	CONSTRAINT "product_complaint_media_pkey" PRIMARY KEY("psid","mid")
);
--> statement-breakpoint
CREATE TABLE "vendor_complaint_media" (
	"mid" integer NOT NULL,
	"vcid" integer NOT NULL,
	CONSTRAINT "vendor_complaint_media_pkey" PRIMARY KEY("mid","vcid")
);
--> statement-breakpoint
CREATE TABLE "managers_access_permits" (
	"maid" integer NOT NULL,
	"mapid" integer NOT NULL,
	CONSTRAINT "managers_access_permits_pkey" PRIMARY KEY("maid","mapid")
);
--> statement-breakpoint
CREATE TABLE "vendor_review_media" (
	"vrid" integer NOT NULL,
	"mid" integer NOT NULL,
	CONSTRAINT "vendor_review_media_pkey" PRIMARY KEY("vrid","mid")
);
--> statement-breakpoint
CREATE TABLE "client_fav_products" (
	"created_at" timestamp DEFAULT now(),
	"client_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	CONSTRAINT "client_fav_products_pkey" PRIMARY KEY("client_id","product_id")
);
--> statement-breakpoint
CREATE TABLE "admin_notification_read_states" (
	"anid" bigint NOT NULL,
	"maid" integer NOT NULL,
	"read_at" timestamp DEFAULT now(),
	CONSTRAINT "admin_notification_read_states_pkey" PRIMARY KEY("anid","maid")
);
--> statement-breakpoint
CREATE TABLE "d_country_values_localizations" (
	"id" integer NOT NULL,
	"name" varchar(100),
	"language" "language_variants" NOT NULL,
	CONSTRAINT "d_country_values_localizations_pkey" PRIMARY KEY("id","language")
);
--> statement-breakpoint
CREATE TABLE "d_brand_values_localizations" (
	"id" integer NOT NULL,
	"name" varchar(100),
	"language" "language_variants" NOT NULL,
	CONSTRAINT "d_brand_values_localizations_pkey" PRIMARY KEY("id","language")
);
--> statement-breakpoint
CREATE TABLE "d_transport_companies_localizations" (
	"id" integer NOT NULL,
	"name" varchar(100),
	"language" "language_variants" NOT NULL,
	CONSTRAINT "d_transport_companies_localizations_pkey" PRIMARY KEY("id","language")
);
--> statement-breakpoint
CREATE TABLE "global_discount_members" (
	"gdid" integer NOT NULL,
	"vid" integer NOT NULL,
	"is_pending" boolean DEFAULT false NOT NULL,
	CONSTRAINT "global_discount_members_pkey" PRIMARY KEY("gdid","vid")
);
--> statement-breakpoint
CREATE TABLE "d_custom_values_localizations" (
	"id" integer NOT NULL,
	"name" varchar(100),
	"language" "language_variants" NOT NULL,
	CONSTRAINT "d_custom_values_localizations_pkey" PRIMARY KEY("id","language")
);
--> statement-breakpoint
CREATE TABLE "product_category_localizations" (
	"pcid" integer NOT NULL,
	"name" varchar(100),
	"category_mid" integer,
	"language" "language_variants" NOT NULL,
	CONSTRAINT "product_category_localizations_pkey" PRIMARY KEY("pcid","language")
);
--> statement-breakpoint
CREATE TABLE "product_media" (
	"created_at" timestamp DEFAULT now(),
	"pid" integer NOT NULL,
	"media_id" integer NOT NULL,
	"language" "language_variants" NOT NULL,
	CONSTRAINT "product_media_pkey" PRIMARY KEY("pid","media_id","language")
);
--> statement-breakpoint
CREATE TABLE "product_category_prop_localization" (
	"pcpid" integer NOT NULL,
	"name" varchar(200),
	"tip" varchar(200),
	"language" "language_variants" NOT NULL,
	CONSTRAINT "product_category_prop_localization_pkey" PRIMARY KEY("pcpid","language")
);
--> statement-breakpoint
CREATE TABLE "product_custom_prop_localizations" (
	"pcpid" integer NOT NULL,
	"name" varchar(200),
	"description" varchar(1000),
	"language" "language_variants" NOT NULL,
	CONSTRAINT "product_custom_prop_localizations_pkey" PRIMARY KEY("pcpid","language")
);
--> statement-breakpoint
CREATE TABLE "product_remains" (
	"pid" integer NOT NULL,
	"vid" integer NOT NULL,
	"updated_at" timestamp,
	"volume" integer DEFAULT 0 NOT NULL,
	"country" integer NOT NULL,
	CONSTRAINT "product_remains_pkey" PRIMARY KEY("pid","vid","country")
);
--> statement-breakpoint
CREATE TABLE "product_localizations" (
	"pid" integer NOT NULL,
	"name" varchar(200),
	"title" varchar(200),
	"description" text,
	"comment" varchar(1000),
	"language" "language_variants" NOT NULL,
	CONSTRAINT "product_localizations_pkey" PRIMARY KEY("pid","language")
);
--> statement-breakpoint
CREATE TABLE "article_publication_localizations" (
	"apid" integer NOT NULL,
	"main_mid" integer,
	"title" varchar(200),
	"annotation" varchar(500),
	"text" text,
	"language" "language_variants" NOT NULL,
	CONSTRAINT "article_publication_localizations_pkey" PRIMARY KEY("apid","language")
);
--> statement-breakpoint
CREATE TABLE "news_publication_localizations" (
	"npid" integer NOT NULL,
	"main_mid" integer,
	"title" varchar(200),
	"annotation" varchar(500),
	"text" text,
	"language" "language_variants" NOT NULL,
	CONSTRAINT "news_publication_localizations_pkey" PRIMARY KEY("npid","language")
);
--> statement-breakpoint
ALTER TABLE "client_payout_requests" ADD CONSTRAINT "client_payout_requests_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_payout_requests" ADD CONSTRAINT "client_payout_requests_cpr_fkey" FOREIGN KEY ("cpr") REFERENCES "public"."client_payout_requisites"("cpr") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_referrals" ADD CONSTRAINT "client_referrals_owner_cid_fkey" FOREIGN KEY ("owner_cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_referrals" ADD CONSTRAINT "client_referrals_refferer_cid_fkey" FOREIGN KEY ("refferer_cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_avatar_id_fkey" FOREIGN KEY ("avatar_id") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_payout_requisites" ADD CONSTRAINT "client_payout_requisites_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_referrals_account_transactions" ADD CONSTRAINT "client_referrals_account_transactions_crid_fkey" FOREIGN KEY ("crid") REFERENCES "public"."client_referrals"("crid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_refunds" ADD CONSTRAINT "product_refunds_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_refunds" ADD CONSTRAINT "product_refunds_oid_fkey" FOREIGN KEY ("oid") REFERENCES "public"."orders"("oid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_refunds" ADD CONSTRAINT "product_refunds_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_card_tokens" ADD CONSTRAINT "bank_card_tokens_caid_fkey" FOREIGN KEY ("caid") REFERENCES "public"."client_addresses"("caid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_requisites" ADD CONSTRAINT "vendor_requisites_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendors" ADD CONSTRAINT "vendors_avatar_id_fkey" FOREIGN KEY ("avatar_id") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_account_transactions" ADD CONSTRAINT "vendor_account_transactions_vaid_fkey" FOREIGN KEY ("vaid") REFERENCES "public"."vendor_accounts"("vaid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_payout_requests" ADD CONSTRAINT "vendor_payout_requests_vaid_fkey" FOREIGN KEY ("vaid") REFERENCES "public"."vendor_accounts"("vaid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_payout_requests" ADD CONSTRAINT "vendor_payout_requests_vbrid_fkey" FOREIGN KEY ("vbrid") REFERENCES "public"."vendor_bank_requisites"("vbrid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_addresses" ADD CONSTRAINT "client_addresses_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_addresses" ADD CONSTRAINT "client_addresses_transport_company_fkey" FOREIGN KEY ("transport_company") REFERENCES "public"."d_transport_companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_phone_auth" ADD CONSTRAINT "vendor_phone_auth_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clients_phone_auth" ADD CONSTRAINT "clients_phone_auth_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."d_countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manager_password_auth" ADD CONSTRAINT "manager_password_auth_manager_id_fkey" FOREIGN KEY ("manager_id") REFERENCES "public"."managers"("maid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_vendor_owner_id_fkey" FOREIGN KEY ("vendor_owner_id") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_pcid_fkey" FOREIGN KEY ("pcid") REFERENCES "public"."product_categories"("pcid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."d_countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "public"."d_brands"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_subscribers" ADD CONSTRAINT "product_subscribers_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_subscribers" ADD CONSTRAINT "product_subscribers_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_subscribers" ADD CONSTRAINT "product_subscribers_product_price_fkey" FOREIGN KEY ("product_price") REFERENCES "public"."product_prices"("ppid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_sub_bills" ADD CONSTRAINT "product_sub_bills_psid_fkey" FOREIGN KEY ("psid") REFERENCES "public"."product_subscribers"("psid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_reviews" ADD CONSTRAINT "product_reviews_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_reviews" ADD CONSTRAINT "product_reviews_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_reviews" ADD CONSTRAINT "client_reviews_to_cid_fkey" FOREIGN KEY ("to_cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_reviews" ADD CONSTRAINT "client_reviews_from_vid_fkey" FOREIGN KEY ("from_vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_categories" ADD CONSTRAINT "product_categories_parent_category_id_fkey" FOREIGN KEY ("parent_category_id") REFERENCES "public"."product_categories"("pcid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_client_address_id_fkey" FOREIGN KEY ("client_address_id") REFERENCES "public"."client_addresses"("caid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_cpmid_fkey" FOREIGN KEY ("cpmid") REFERENCES "public"."client_payment_methods"("cpmid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "local_discounts" ADD CONSTRAINT "local_discounts_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_to_products" ADD CONSTRAINT "order_to_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_to_products" ADD CONSTRAINT "order_to_products_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("oid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recommended_products" ADD CONSTRAINT "recommended_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recommended_products" ADD CONSTRAINT "recommended_products_recommended_good_id_fkey" FOREIGN KEY ("recommended_good_id") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_complaints" ADD CONSTRAINT "product_complaints_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_complaints" ADD CONSTRAINT "product_complaints_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notifications" ADD CONSTRAINT "admin_notifications_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notifications" ADD CONSTRAINT "admin_notifications_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notifications" ADD CONSTRAINT "admin_notifications_prid_fkey" FOREIGN KEY ("prid") REFERENCES "public"."product_reviews"("prid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notifications" ADD CONSTRAINT "admin_notifications_pcid_fkey" FOREIGN KEY ("pcid") REFERENCES "public"."product_complaints"("psid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notifications" ADD CONSTRAINT "admin_notifications_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notifications" ADD CONSTRAINT "admin_notifications_prfid_fkey" FOREIGN KEY ("prfid") REFERENCES "public"."product_refunds"("prfid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_sessions" ADD CONSTRAINT "auth_sessions_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_sessions" ADD CONSTRAINT "auth_sessions_manager_id_fkey" FOREIGN KEY ("manager_id") REFERENCES "public"."managers"("maid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth_sessions" ADD CONSTRAINT "auth_sessions_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_complaints" ADD CONSTRAINT "vendor_complaints_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_complaints" ADD CONSTRAINT "vendor_complaints_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_geolocations" ADD CONSTRAINT "user_geolocations_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_oid_fkey" FOREIGN KEY ("oid") REFERENCES "public"."orders"("oid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_avatar_mid_fkey" FOREIGN KEY ("avatar_mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_category_props" ADD CONSTRAINT "product_category_props_pcid_fkey" FOREIGN KEY ("pcid") REFERENCES "public"."product_categories"("pcid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_participants" ADD CONSTRAINT "conv_participants_convid_fkey" FOREIGN KEY ("convid") REFERENCES "public"."conversations"("convid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_participants" ADD CONSTRAINT "conv_participants_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_participants" ADD CONSTRAINT "conv_participants_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_participants" ADD CONSTRAINT "conv_participants_maid_fkey" FOREIGN KEY ("maid") REFERENCES "public"."managers"("maid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_participants" ADD CONSTRAINT "conv_participants_last_read_mesid_fkey" FOREIGN KEY ("last_read_mesid") REFERENCES "public"."conv_messages"("mesid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_messages" ADD CONSTRAINT "conv_messages_convid_fkey" FOREIGN KEY ("convid") REFERENCES "public"."conversations"("convid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_messages" ADD CONSTRAINT "conv_messages_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_messages" ADD CONSTRAINT "conv_messages_cid_fkey" FOREIGN KEY ("cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conv_messages" ADD CONSTRAINT "conv_messages_maid_fkey" FOREIGN KEY ("maid") REFERENCES "public"."managers"("maid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manager_notifications" ADD CONSTRAINT "manager_notifications_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "public"."system_notifications"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manager_notifications" ADD CONSTRAINT "manager_notifications_manager_id_fkey" FOREIGN KEY ("manager_id") REFERENCES "public"."managers"("maid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_bank_requisites" ADD CONSTRAINT "vendor_bank_requisites_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_bank_requisites" ADD CONSTRAINT "vendor_bank_requisites_vrqid_fkey" FOREIGN KEY ("vrqid") REFERENCES "public"."vendor_requisites"("vrqid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_accounts" ADD CONSTRAINT "vendor_accounts_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_payment_methods" ADD CONSTRAINT "client_payment_methods_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_reviews" ADD CONSTRAINT "vendor_reviews_to_vid_fkey" FOREIGN KEY ("to_vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_reviews" ADD CONSTRAINT "vendor_reviews_from_cid_fkey" FOREIGN KEY ("from_cid") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_notifications" ADD CONSTRAINT "system_notifications_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_notifications" ADD CONSTRAINT "system_notifications_prid_fkey" FOREIGN KEY ("prid") REFERENCES "public"."product_reviews"("prid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_notifications" ADD CONSTRAINT "system_notifications_complaint_id_fkey" FOREIGN KEY ("complaint_id") REFERENCES "public"."product_complaints"("psid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_notifications" ADD CONSTRAINT "system_notifications_prfid_fkey" FOREIGN KEY ("prfid") REFERENCES "public"."product_refunds"("prfid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_refund_media" ADD CONSTRAINT "product_refund_media_mid_fkey" FOREIGN KEY ("mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_refund_media" ADD CONSTRAINT "product_refund_media_prfid_fkey" FOREIGN KEY ("prfid") REFERENCES "public"."product_refunds"("prfid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_props" ADD CONSTRAINT "product_props_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_props" ADD CONSTRAINT "product_props_pcpid_fkey" FOREIGN KEY ("pcpid") REFERENCES "public"."product_custom_props"("pcpid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_review_media" ADD CONSTRAINT "product_review_media_prid_fkey" FOREIGN KEY ("prid") REFERENCES "public"."product_reviews"("prid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_review_media" ADD CONSTRAINT "product_review_media_mid_fkey" FOREIGN KEY ("mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_review_media" ADD CONSTRAINT "client_review_media_crid_fkey" FOREIGN KEY ("crid") REFERENCES "public"."client_reviews"("crid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_review_media" ADD CONSTRAINT "client_review_media_mid_fkey" FOREIGN KEY ("mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "category_discounts" ADD CONSTRAINT "category_discounts_discount_id_fkey" FOREIGN KEY ("discount_id") REFERENCES "public"."global_discounts"("gdid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "category_discounts" ADD CONSTRAINT "category_discounts_pcid_fkey" FOREIGN KEY ("pcid") REFERENCES "public"."product_categories"("pcid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_product_discounts" ADD CONSTRAINT "vendor_product_discounts_ldid_fkey" FOREIGN KEY ("ldid") REFERENCES "public"."local_discounts"("ldid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_product_discounts" ADD CONSTRAINT "vendor_product_discounts_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_complaint_media" ADD CONSTRAINT "product_complaint_media_psid_fkey" FOREIGN KEY ("psid") REFERENCES "public"."product_complaints"("psid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_complaint_media" ADD CONSTRAINT "product_complaint_media_mid_fkey" FOREIGN KEY ("mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_complaint_media" ADD CONSTRAINT "vendor_complaint_media_mid_fkey" FOREIGN KEY ("mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_complaint_media" ADD CONSTRAINT "vendor_complaint_media_vcid_fkey" FOREIGN KEY ("vcid") REFERENCES "public"."vendor_complaints"("vcid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "managers_access_permits" ADD CONSTRAINT "managers_access_permits_maid_fkey" FOREIGN KEY ("maid") REFERENCES "public"."managers"("maid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "managers_access_permits" ADD CONSTRAINT "managers_access_permits_mapid_fkey" FOREIGN KEY ("mapid") REFERENCES "public"."access_permits"("apid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_review_media" ADD CONSTRAINT "vendor_review_media_vrid_fkey" FOREIGN KEY ("vrid") REFERENCES "public"."vendor_reviews"("vrid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_review_media" ADD CONSTRAINT "vendor_review_media_mid_fkey" FOREIGN KEY ("mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_fav_products" ADD CONSTRAINT "client_fav_products_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("cid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_fav_products" ADD CONSTRAINT "client_fav_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notification_read_states" ADD CONSTRAINT "admin_notification_read_states_anid_fkey" FOREIGN KEY ("anid") REFERENCES "public"."admin_notifications"("anid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_notification_read_states" ADD CONSTRAINT "admin_notification_read_states_maid_fkey" FOREIGN KEY ("maid") REFERENCES "public"."managers"("maid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "d_country_values_localizations" ADD CONSTRAINT "d_country_values_localizations_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."d_countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "d_brand_values_localizations" ADD CONSTRAINT "d_brand_values_localizations_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."d_brands"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "d_transport_companies_localizations" ADD CONSTRAINT "d_transport_companies_localizations_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."d_transport_companies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "global_discount_members" ADD CONSTRAINT "global_discount_members_gdid_fkey" FOREIGN KEY ("gdid") REFERENCES "public"."global_discounts"("gdid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "global_discount_members" ADD CONSTRAINT "global_discount_members_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "d_custom_values_localizations" ADD CONSTRAINT "d_custom_values_localizations_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."d_custom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_category_localizations" ADD CONSTRAINT "product_category_localizations_pcid_fkey" FOREIGN KEY ("pcid") REFERENCES "public"."product_categories"("pcid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_category_localizations" ADD CONSTRAINT "product_category_localizations_category_mid_fkey" FOREIGN KEY ("category_mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_category_prop_localization" ADD CONSTRAINT "product_category_prop_localization_pcpid_fkey" FOREIGN KEY ("pcpid") REFERENCES "public"."product_category_props"("pcpid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_custom_prop_localizations" ADD CONSTRAINT "product_custom_prop_localizations_pcpid_fkey" FOREIGN KEY ("pcpid") REFERENCES "public"."product_custom_props"("pcpid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_remains" ADD CONSTRAINT "product_remains_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_remains" ADD CONSTRAINT "product_remains_vid_fkey" FOREIGN KEY ("vid") REFERENCES "public"."vendors"("vid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_remains" ADD CONSTRAINT "product_remains_country_fkey" FOREIGN KEY ("country") REFERENCES "public"."d_countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_localizations" ADD CONSTRAINT "product_localizations_pid_fkey" FOREIGN KEY ("pid") REFERENCES "public"."products"("pid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "article_publication_localizations" ADD CONSTRAINT "article_publication_localizations_apid_fkey" FOREIGN KEY ("apid") REFERENCES "public"."article_publications"("apid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "article_publication_localizations" ADD CONSTRAINT "article_publication_localizations_main_mid_fkey" FOREIGN KEY ("main_mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news_publication_localizations" ADD CONSTRAINT "news_publication_localizations_npid_fkey" FOREIGN KEY ("npid") REFERENCES "public"."news_publications"("npid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news_publication_localizations" ADD CONSTRAINT "news_publication_localizations_main_mid_fkey" FOREIGN KEY ("main_mid") REFERENCES "public"."media"("mid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_audit_actor" ON "audit_log" USING btree ("actor_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_audit_created_at" ON "audit_log" USING btree ("created_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_audit_record" ON "audit_log" USING btree ("table_name" text_ops,"record_id" text_ops);--> statement-breakpoint
CREATE INDEX "idx_vat_account" ON "vendor_account_transactions" USING btree ("vaid" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_vat_account_time" ON "vendor_account_transactions" USING btree ("vaid" int4_ops,"created_at" int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "product_prices_country_id_pid_duration_idx" ON "product_prices" USING btree ("country_id" float8_ops,"pid" int4_ops,"duration" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_products_brand" ON "products" USING btree ("brand_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_products_category" ON "products" USING btree ("pcid" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_products_category_vendor" ON "products" USING btree ("pcid" int4_ops,"vendor_owner_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_products_country" ON "products" USING btree ("country_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_products_vendor_id" ON "products" USING btree ("vendor_owner_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_psb_subscriber" ON "product_sub_bills" USING btree ("psid" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_reviews_product" ON "product_reviews" USING btree ("pid" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_reviews_state" ON "product_reviews" USING btree ("review_state_variant" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_orders_client" ON "orders" USING btree ("client_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_orders_client_state" ON "orders" USING btree ("client_id" int4_ops,"order_state" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_orders_state" ON "orders" USING btree ("order_state" enum_ops);--> statement-breakpoint
CREATE INDEX "idx_otp_order_id" ON "order_to_products" USING btree ("order_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_otp_product_id" ON "order_to_products" USING btree ("product_id" int4_ops);--> statement-breakpoint
CREATE INDEX "idx_messages_convid" ON "conv_messages" USING btree ("convid" int8_ops);--> statement-breakpoint
CREATE INDEX "idx_messages_convid_time" ON "conv_messages" USING btree ("convid" int8_ops,"created_at" int8_ops);--> statement-breakpoint
CREATE INDEX "idx_custom_props_value" ON "product_custom_props" USING gin ("value" jsonb_ops);
*/